export type TimeoutConfigValueType = "int" | "float";
export type TimeoutConfigService = "shared" | "game-service" | "ai-engine";
export type TimeoutConfigSectionKind = "flow" | "extra" | "infra";

export interface TimeoutConfigSectionMeta {
  id: string;
  kind: TimeoutConfigSectionKind;
  order: number;
  tag: string;
  title: string;
  description: string;
}

export interface TimeoutConfigCatalogEntry {
  key: string;
  defaultValue: string;
  description: string;
  service: TimeoutConfigService;
  group: string;
  unit: "ms" | "s" | "ratio";
  valueType: TimeoutConfigValueType;
  sectionId: string;
  sectionKind: TimeoutConfigSectionKind;
  sectionOrder: number;
  sectionTag: string;
  sectionTitle: string;
  sectionDescription: string;
  itemOrder: number;
}

const TIMEOUT_CONFIG_SECTIONS: Record<string, TimeoutConfigSectionMeta> = {
  step1_intent_freeze: {
    id: "step1_intent_freeze",
    kind: "flow",
    order: 10,
    tag: "Step 1",
    title: "Intent Freeze",
    description: "Prompt expansion and create-entry watchdogs.",
  },
  step2_spec_contract: {
    id: "step2_spec_contract",
    kind: "flow",
    order: 20,
    tag: "Step 2",
    title: "Spec & Contract",
    description:
      "Single-shot intent parsing and spec compilation timeout budgets.",
  },
  step3_code_synthesis: {
    id: "step3_code_synthesis",
    kind: "flow",
    order: 30,
    tag: "Step 3",
    title: "Code Synthesis",
    description: "Primary create-generation timeout ceilings.",
  },
  step4_issue_repair: {
    id: "step4_issue_repair",
    kind: "flow",
    order: 40,
    tag: "Step 4",
    title: "Issue Repair & Runtime QA",
    description: "QA repair windows and runtime validation watchdog budgets.",
  },
  step5_finalize: {
    id: "step5_finalize",
    kind: "flow",
    order: 50,
    tag: "Step 5",
    title: "Finalize",
    description:
      "Deterministic finalize currently has no standalone timeout knobs.",
  },
  extra_iterate: {
    id: "extra_iterate",
    kind: "extra",
    order: 60,
    tag: "Extra",
    title: "Iterate Flow",
    description:
      "Iterate classify and rewrite budgets outside the main create path.",
  },
  extra_tools: {
    id: "extra_tools",
    kind: "extra",
    order: 70,
    tag: "Extra",
    title: "Auxiliary Tools",
    description: "Prompt expansion and other sidecar tools.",
  },
  infra_pipeline: {
    id: "infra_pipeline",
    kind: "infra",
    order: 80,
    tag: "Infra",
    title: "Pipeline Guardrails",
    description: "Cross-service total-deadline and buffer settings.",
  },
  infra_transport: {
    id: "infra_transport",
    kind: "infra",
    order: 90,
    tag: "Infra",
    title: "Upstream Transport",
    description:
      "game-service to ai-engine request, polling, and cancellation timeouts.",
  },
  infra_relay: {
    id: "infra_relay",
    kind: "infra",
    order: 100,
    tag: "Infra",
    title: "Relay Backchannel",
    description:
      "ai-engine callbacks that report progress, artifacts, and failure details.",
  },
  infra_config: {
    id: "infra_config",
    kind: "infra",
    order: 110,
    tag: "Infra",
    title: "Config & Gateway Cache",
    description:
      "Admin refresh, config-store reads, and gateway cache refresh windows.",
  },
  infra_tasking: {
    id: "infra_tasking",
    kind: "infra",
    order: 120,
    tag: "Infra",
    title: "Background Tasking",
    description:
      "Sweep loops, heartbeat cadence, and completed-task retention.",
  },
};

type TimeoutConfigEntryInput = Omit<
  TimeoutConfigCatalogEntry,
  | "sectionKind"
  | "sectionOrder"
  | "sectionTag"
  | "sectionTitle"
  | "sectionDescription"
>;

function entry(input: TimeoutConfigEntryInput): TimeoutConfigCatalogEntry {
  const section = TIMEOUT_CONFIG_SECTIONS[input.sectionId];
  if (!section) {
    throw new Error(`Unknown timeout config section: ${input.sectionId}`);
  }
  return {
    ...input,
    sectionKind: section.kind,
    sectionOrder: section.order,
    sectionTag: section.tag,
    sectionTitle: section.title,
    sectionDescription: section.description,
  };
}

export const TIMEOUT_CONFIG_CATALOG: TimeoutConfigCatalogEntry[] = [
  entry({
    key: "timeout.game_service.creation_session_init_ms",
    defaultValue: "45000",
    description:
      "Creation-session init watchdog. Must stay above the prompt-expansion round trip.",
    service: "game-service",
    group: "pipeline",
    unit: "ms",
    valueType: "int",
    sectionId: "step1_intent_freeze",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.ai_engine.intent_parse.request_s",
    defaultValue: "45",
    description:
      "Single-shot intent-parse request timeout for create / iterate spec compilation.",
    service: "ai-engine",
    group: "intent",
    unit: "s",
    valueType: "int",
    sectionId: "step2_spec_contract",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.ai_engine.intent_parse.overall_s",
    defaultValue: "90",
    description:
      "Single-shot intent-parse overall timeout including timeout-retry headroom.",
    service: "ai-engine",
    group: "intent",
    unit: "s",
    valueType: "int",
    sectionId: "step2_spec_contract",
    itemOrder: 20,
  }),
  entry({
    key: "timeout.ai_engine.llm_long_generation_s",
    defaultValue: "240",
    description:
      "Create-path long generation ceiling used by code synthesis budgets.",
    service: "ai-engine",
    group: "llm",
    unit: "s",
    valueType: "int",
    sectionId: "step3_code_synthesis",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.ai_engine.qa_repair_s",
    defaultValue: "180",
    description: "Whole-document QA repair request timeout.",
    service: "ai-engine",
    group: "qa",
    unit: "s",
    valueType: "int",
    sectionId: "step4_issue_repair",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.ai_engine.qa_fast_repair_s",
    defaultValue: "120",
    description:
      "Smaller QA repair timeout for targeted syntax or structural fixes.",
    service: "ai-engine",
    group: "qa",
    unit: "s",
    valueType: "int",
    sectionId: "step4_issue_repair",
    itemOrder: 20,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.base_s",
    defaultValue: "8",
    description:
      "Base runtime-QA timeout before code-size bonuses are applied.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 30,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.phase_launch_s",
    defaultValue: "8",
    description: "Browser launch phase budget inside runtime QA.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 40,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.phase_content_load_s",
    defaultValue: "15",
    description: "Content-load phase budget inside runtime QA.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 50,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.phase_interaction_s",
    defaultValue: "6",
    description: "Interaction probe phase budget inside runtime QA.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 60,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.phase_collect_s",
    defaultValue: "5",
    description: "Result collection phase budget inside runtime QA.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 70,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.phase_total_headroom_s",
    defaultValue: "3",
    description:
      "Outer watchdog headroom above summed runtime-QA phase budgets.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 80,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.max_s",
    defaultValue: "30",
    description: "Hard cap for runtime-QA total timeout after bonuses.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 90,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.bonus_ge_16000_s",
    defaultValue: "2",
    description:
      "Extra runtime-QA seconds once candidate code size reaches 16KB.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 100,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.bonus_ge_24000_s",
    defaultValue: "2",
    description:
      "Extra runtime-QA seconds once candidate code size reaches 24KB.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 110,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.bonus_ge_32000_s",
    defaultValue: "10",
    description:
      "Extra runtime-QA seconds once candidate code size reaches 32KB.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 120,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.bonus_ge_40000_s",
    defaultValue: "4",
    description:
      "Extra runtime-QA seconds once candidate code size reaches 40KB.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 130,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.remediation_bonus_per_attempt_s",
    defaultValue: "4",
    description:
      "Per-remediation bonus while runtime QA is retrying fixed candidates.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 140,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.remediation_bonus_max_s",
    defaultValue: "8",
    description: "Maximum remediation bonus that runtime QA may add.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 150,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.remediation_large_code_floor_s",
    defaultValue: "8",
    description:
      "Minimum extra runtime-QA time for large-code remediation rounds.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 160,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.load_wait_factor_ms_per_s",
    defaultValue: "250",
    description:
      "Scaling factor used to convert runtime-QA timeout into page-load wait time.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "ms",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 170,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.load_wait_min_ms",
    defaultValue: "250",
    description: "Minimum page-load wait time inside runtime QA.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "ms",
    valueType: "int",
    sectionId: "step4_issue_repair",
    itemOrder: 180,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.initial_wait_ratio",
    defaultValue: "0.25",
    description:
      "Post-render wait ratio applied before the first runtime-QA probe.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "ratio",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 190,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.initial_wait_min_s",
    defaultValue: "0.35",
    description: "Minimum post-render wait before the first runtime-QA probe.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 200,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.initial_wait_max_s",
    defaultValue: "2",
    description: "Maximum post-render wait before the first runtime-QA probe.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 210,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.post_wait_ratio",
    defaultValue: "0.15",
    description:
      "Post-interaction wait ratio before collecting runtime-QA evidence.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "ratio",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 220,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.post_wait_min_s",
    defaultValue: "0.15",
    description:
      "Minimum post-interaction wait before collecting runtime-QA evidence.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 230,
  }),
  entry({
    key: "timeout.ai_engine.runtime_qa.post_wait_max_s",
    defaultValue: "0.8",
    description:
      "Maximum post-interaction wait before collecting runtime-QA evidence.",
    service: "ai-engine",
    group: "runtime_qa",
    unit: "s",
    valueType: "float",
    sectionId: "step4_issue_repair",
    itemOrder: 240,
  }),
  entry({
    key: "timeout.ai_engine.iterate.classify_request_s",
    defaultValue: "30",
    description: "Iterate classify request timeout.",
    service: "ai-engine",
    group: "iterate",
    unit: "s",
    valueType: "int",
    sectionId: "extra_iterate",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.ai_engine.iterate.classify_overall_s",
    defaultValue: "60",
    description:
      "Iterate classify overall timeout including timeout-retry headroom.",
    service: "ai-engine",
    group: "iterate",
    unit: "s",
    valueType: "int",
    sectionId: "extra_iterate",
    itemOrder: 20,
  }),
  entry({
    key: "timeout.ai_engine.iterate.param_adjust_request_s",
    defaultValue: "90",
    description:
      "LLM fallback request timeout for iterate param-adjust rewrites.",
    service: "ai-engine",
    group: "iterate",
    unit: "s",
    valueType: "int",
    sectionId: "extra_iterate",
    itemOrder: 30,
  }),
  entry({
    key: "timeout.ai_engine.iterate.param_adjust_overall_s",
    defaultValue: "180",
    description:
      "LLM fallback overall timeout for iterate param-adjust rewrites.",
    service: "ai-engine",
    group: "iterate",
    unit: "s",
    valueType: "int",
    sectionId: "extra_iterate",
    itemOrder: 40,
  }),
  entry({
    key: "timeout.ai_engine.iterate.element_change_request_s",
    defaultValue: "120",
    description: "Request timeout for iterate.element_change patch generation.",
    service: "ai-engine",
    group: "iterate",
    unit: "s",
    valueType: "int",
    sectionId: "extra_iterate",
    itemOrder: 50,
  }),
  entry({
    key: "timeout.ai_engine.iterate.element_change_overall_s",
    defaultValue: "240",
    description:
      "Overall timeout for iterate.element_change including retry / fallback headroom.",
    service: "ai-engine",
    group: "iterate",
    unit: "s",
    valueType: "int",
    sectionId: "extra_iterate",
    itemOrder: 60,
  }),
  entry({
    key: "timeout.ai_engine.iterate.mechanic_change_request_s",
    defaultValue: "135",
    description: "Request timeout for iterate.mechanic_change rewrites.",
    service: "ai-engine",
    group: "iterate",
    unit: "s",
    valueType: "int",
    sectionId: "extra_iterate",
    itemOrder: 70,
  }),
  entry({
    key: "timeout.ai_engine.iterate.mechanic_change_overall_s",
    defaultValue: "270",
    description:
      "Overall timeout for iterate.mechanic_change including retry / fallback headroom.",
    service: "ai-engine",
    group: "iterate",
    unit: "s",
    valueType: "int",
    sectionId: "extra_iterate",
    itemOrder: 80,
  }),
  entry({
    key: "timeout.game_service.expand_prompt_request_ms",
    defaultValue: "30000",
    description:
      "Prompt expansion request timeout from game-service to ai-engine.",
    service: "game-service",
    group: "tooling",
    unit: "ms",
    valueType: "int",
    sectionId: "extra_tools",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.pipeline.default_s",
    defaultValue: "1800",
    description:
      "Default total generation timeout when create / iterate does not pass timeoutS explicitly.",
    service: "shared",
    group: "pipeline",
    unit: "s",
    valueType: "int",
    sectionId: "infra_pipeline",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.pipeline.v2_min_s",
    defaultValue: "1800",
    description: "Minimum allowed total timeout for the five-step V2 pipeline.",
    service: "shared",
    group: "pipeline",
    unit: "s",
    valueType: "int",
    sectionId: "infra_pipeline",
    itemOrder: 20,
  }),
  entry({
    key: "timeout.game_service.upstream_timeout_buffer_s",
    defaultValue: "60",
    description:
      "Extra wait buffer that game-service adds beyond the upstream task timeout.",
    service: "game-service",
    group: "pipeline",
    unit: "s",
    valueType: "int",
    sectionId: "infra_pipeline",
    itemOrder: 30,
  }),
  entry({
    key: "timeout.game_service.upstream_deadline_grace_ms",
    defaultValue: "30000",
    description:
      "Additional local grace period after the upstream timeout buffer is exhausted.",
    service: "game-service",
    group: "pipeline",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_pipeline",
    itemOrder: 40,
  }),
  entry({
    key: "timeout.game_service.upstream_request_ms",
    defaultValue: "30000",
    description:
      "Create / iterate task submission timeout from game-service to ai-engine.",
    service: "game-service",
    group: "http",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_transport",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.game_service.upstream_request_retry_delay_ms",
    defaultValue: "3000",
    description: "Retry delay after game-service task submission fails.",
    service: "game-service",
    group: "http",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_transport",
    itemOrder: 20,
  }),
  entry({
    key: "timeout.game_service.upstream_snapshot_ms",
    defaultValue: "10000",
    description: "Timeout for polling ai-engine task snapshots.",
    service: "game-service",
    group: "http",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_transport",
    itemOrder: 30,
  }),
  entry({
    key: "timeout.game_service.upstream_cancel_ms",
    defaultValue: "10000",
    description: "Timeout for canceling ai-engine tasks.",
    service: "game-service",
    group: "http",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_transport",
    itemOrder: 40,
  }),
  entry({
    key: "timeout.ai_engine.progress_relay_s",
    defaultValue: "3",
    description:
      "Progress callback timeout from ai-engine back to game-service.",
    service: "ai-engine",
    group: "relay",
    unit: "s",
    valueType: "float",
    sectionId: "infra_relay",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.ai_engine.artifact_relay_s",
    defaultValue: "5",
    description:
      "Artifact callback timeout from ai-engine back to game-service.",
    service: "ai-engine",
    group: "relay",
    unit: "s",
    valueType: "float",
    sectionId: "infra_relay",
    itemOrder: 20,
  }),
  entry({
    key: "timeout.ai_engine.stage_summary_relay_s",
    defaultValue: "5",
    description:
      "Stage-summary callback timeout from ai-engine back to game-service.",
    service: "ai-engine",
    group: "relay",
    unit: "s",
    valueType: "float",
    sectionId: "infra_relay",
    itemOrder: 30,
  }),
  entry({
    key: "timeout.ai_engine.task_failure_relay_s",
    defaultValue: "5",
    description:
      "Failure-detail callback timeout from ai-engine back to game-service.",
    service: "ai-engine",
    group: "relay",
    unit: "s",
    valueType: "float",
    sectionId: "infra_relay",
    itemOrder: 40,
  }),
  entry({
    key: "timeout.ai_engine.llm_call_log_relay_s",
    defaultValue: "3",
    description:
      "LLM call-log callback timeout from ai-engine back to game-service.",
    service: "ai-engine",
    group: "relay",
    unit: "s",
    valueType: "float",
    sectionId: "infra_relay",
    itemOrder: 50,
  }),
  entry({
    key: "timeout.ai_engine.task_activity_relay_s",
    defaultValue: "3",
    description:
      "Task-activity callback timeout from ai-engine back to game-service.",
    service: "ai-engine",
    group: "relay",
    unit: "s",
    valueType: "float",
    sectionId: "infra_relay",
    itemOrder: 60,
  }),
  entry({
    key: "timeout.game_service.ai_target_cache_ttl_ms",
    defaultValue: "10000",
    description: "game-service cache lifetime for ai-engine target discovery.",
    service: "game-service",
    group: "routing",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.game_service.admin_refresh_timeout_ms",
    defaultValue: "10000",
    description:
      "Per-node timeout while admin refreshes timeout configs into ai-engine nodes.",
    service: "game-service",
    group: "admin",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 20,
  }),
  entry({
    key: "timeout.ai_engine.llm_fallback_connect_s",
    defaultValue: "15",
    description:
      "Fallback LLM route connect timeout when gateway DB config is unavailable.",
    service: "ai-engine",
    group: "config",
    unit: "s",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 30,
  }),
  entry({
    key: "timeout.ai_engine.llm_gateway_cache_ttl_s",
    defaultValue: "10",
    description:
      "LLM gateway cache TTL for provider / route data loaded from DB.",
    service: "ai-engine",
    group: "config",
    unit: "s",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 40,
  }),
  entry({
    key: "timeout.ai_engine.timeout_store_cache_ttl_s",
    defaultValue: "10",
    description:
      "Timeout-store cache TTL before ai-engine reloads timeout configs from DB.",
    service: "ai-engine",
    group: "config",
    unit: "s",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 50,
  }),
  entry({
    key: "timeout.ai_engine.prompt_store_db_connect_s",
    defaultValue: "5",
    description: "Prompt-store database connect timeout.",
    service: "ai-engine",
    group: "config",
    unit: "s",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 60,
  }),
  entry({
    key: "timeout.ai_engine.prompt_store_db_read_s",
    defaultValue: "5",
    description: "Prompt-store database read timeout.",
    service: "ai-engine",
    group: "config",
    unit: "s",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 70,
  }),
  entry({
    key: "timeout.ai_engine.gateway_db_connect_s",
    defaultValue: "5",
    description: "Gateway database connect timeout.",
    service: "ai-engine",
    group: "config",
    unit: "s",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 80,
  }),
  entry({
    key: "timeout.ai_engine.gateway_db_read_s",
    defaultValue: "5",
    description: "Gateway database read timeout.",
    service: "ai-engine",
    group: "config",
    unit: "s",
    valueType: "int",
    sectionId: "infra_config",
    itemOrder: 90,
  }),
  entry({
    key: "timeout.game_service.active_task_sweep_interval_ms",
    defaultValue: "5000",
    description:
      "Sweep interval for reconciling running generation tasks in game-service.",
    service: "game-service",
    group: "tasking",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_tasking",
    itemOrder: 10,
  }),
  entry({
    key: "timeout.game_service.upstream_poll_interval_ms",
    defaultValue: "1500",
    description:
      "Polling interval while game-service waits for ai-engine task completion.",
    service: "game-service",
    group: "tasking",
    unit: "ms",
    valueType: "int",
    sectionId: "infra_tasking",
    itemOrder: 20,
  }),
  entry({
    key: "timeout.ai_engine.llm_activity_heartbeat_s",
    defaultValue: "15",
    description:
      "LLM activity heartbeat interval emitted while a long request is running.",
    service: "ai-engine",
    group: "tasking",
    unit: "s",
    valueType: "int",
    sectionId: "infra_tasking",
    itemOrder: 30,
  }),
  entry({
    key: "timeout.ai_engine.async_task_completed_ttl_s",
    defaultValue: "86400",
    description:
      "Retention time for completed async tasks kept in ai-engine memory.",
    service: "ai-engine",
    group: "tasking",
    unit: "s",
    valueType: "int",
    sectionId: "infra_tasking",
    itemOrder: 40,
  }),
];

export const TIMEOUT_CONFIG_CATALOG_BY_KEY = new Map(
  TIMEOUT_CONFIG_CATALOG.map((catalogEntry) => [
    catalogEntry.key,
    catalogEntry,
  ]),
);
