export type TimeoutConfigValueType = 'int' | 'float';

export interface TimeoutConfigCatalogEntry {
  key: string;
  defaultValue: string;
  description: string;
  service: 'shared' | 'game-service' | 'ai-engine';
  group: string;
  unit: 'ms' | 's' | 'ratio';
  valueType: TimeoutConfigValueType;
}

export const TIMEOUT_CONFIG_CATALOG: TimeoutConfigCatalogEntry[] = [
  {
    key: 'timeout.pipeline.default_s',
    defaultValue: '1800',
    description: '默认生成任务总超时。create / iterate 未显式传 timeoutS 时使用这个值。',
    service: 'shared',
    group: 'pipeline',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.pipeline.v2_min_s',
    defaultValue: '1800',
    description: 'V2 生成链路允许的最小总超时。用户传入更小值时会被抬到这个下限。',
    service: 'shared',
    group: 'pipeline',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.ai_target_cache_ttl_ms',
    defaultValue: '10000',
    description: 'game-service 缓存 AI engine 目标地址的时长。',
    service: 'game-service',
    group: 'routing',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.active_task_sweep_interval_ms',
    defaultValue: '30000',
    description: '后台 reconcile 运行中 generation task 的扫表间隔。',
    service: 'game-service',
    group: 'tasking',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.admin_refresh_timeout_ms',
    defaultValue: '10000',
    description: '后台刷新 timeout 配置到各 AI engine 节点时的单次 HTTP 超时。',
    service: 'game-service',
    group: 'admin',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.expand_prompt_request_ms',
    defaultValue: '30000',
    description: '扩写提示词时，game-service 调 AI engine 的 HTTP 超时。',
    service: 'game-service',
    group: 'http',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.upstream_request_ms',
    defaultValue: '30000',
    description: '发起异步生成任务时，game-service 调 AI engine 的 HTTP 超时。',
    service: 'game-service',
    group: 'http',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.upstream_request_retry_delay_ms',
    defaultValue: '3000',
    description: '发起异步生成请求失败后的重试等待时间。',
    service: 'game-service',
    group: 'http',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.upstream_snapshot_ms',
    defaultValue: '10000',
    description: '轮询 AI engine 任务状态时，单次 GET /tasks 的 HTTP 超时。',
    service: 'game-service',
    group: 'http',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.upstream_cancel_ms',
    defaultValue: '10000',
    description: '取消上游 AI 任务时，POST /tasks/:id/cancel 的 HTTP 超时。',
    service: 'game-service',
    group: 'http',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.upstream_poll_interval_ms',
    defaultValue: '1500',
    description: '等待 AI engine 任务完成时的轮询间隔。',
    service: 'game-service',
    group: 'tasking',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.upstream_timeout_buffer_s',
    defaultValue: '60',
    description: '在任务总超时之外，game-service 给上游 AI engine 额外预留的等待缓冲。',
    service: 'game-service',
    group: 'pipeline',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.game_service.upstream_deadline_grace_ms',
    defaultValue: '30000',
    description: '轮询等待完成时，在上游缓冲之外再额外追加的本地 deadline 宽限。',
    service: 'game-service',
    group: 'pipeline',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.progress_relay_s',
    defaultValue: '3',
    description: 'AI engine 回传 progress 到 game-service 的 HTTP 超时。',
    service: 'ai-engine',
    group: 'relay',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.artifact_relay_s',
    defaultValue: '5',
    description: 'AI engine 回传 artifact 到 game-service 的 HTTP 超时。',
    service: 'ai-engine',
    group: 'relay',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.stage_summary_relay_s',
    defaultValue: '5',
    description: 'AI engine 回传 stage summary 到 game-service 的 HTTP 超时。',
    service: 'ai-engine',
    group: 'relay',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.task_failure_relay_s',
    defaultValue: '5',
    description: 'AI engine 回传任务失败详情到 game-service 的 HTTP 超时。',
    service: 'ai-engine',
    group: 'relay',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.llm_call_log_relay_s',
    defaultValue: '3',
    description: 'AI engine 回传 LLM call log 到 game-service 的 HTTP 超时。',
    service: 'ai-engine',
    group: 'relay',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.task_activity_relay_s',
    defaultValue: '3',
    description: 'AI engine 回传 task activity 到 game-service 的 HTTP 超时。',
    service: 'ai-engine',
    group: 'relay',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.llm_long_generation_s',
    defaultValue: '240',
    description: '长代码生成阶段的单次 LLM 请求 / overall timeout。',
    service: 'ai-engine',
    group: 'llm',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.qa_repair_s',
    defaultValue: '180',
    description: 'QA 修复阶段的 LLM 请求超时。',
    service: 'ai-engine',
    group: 'qa',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.qa_fast_repair_s',
    defaultValue: '120',
    description: '快速 QA 修复阶段的 LLM 请求超时。',
    service: 'ai-engine',
    group: 'qa',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.base_s',
    defaultValue: '8',
    description: '运行时 QA 的基础超时。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.phase_launch_s',
    defaultValue: '8',
    description: 'Runtime QA browser launch phase timeout.',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.phase_content_load_s',
    defaultValue: '15',
    description: 'Runtime QA content load phase timeout.',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.phase_interaction_s',
    defaultValue: '6',
    description: 'Runtime QA interaction probe phase timeout.',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.phase_collect_s',
    defaultValue: '5',
    description: 'Runtime QA result collection phase timeout.',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.phase_total_headroom_s',
    defaultValue: '3',
    description: 'Runtime QA outer watchdog headroom beyond summed phase budgets.',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.max_s',
    defaultValue: '30',
    description: '运行时 QA 的最大超时上限。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.bonus_ge_16000_s',
    defaultValue: '2',
    description: '候选代码 >= 16KB 时，给运行时 QA 追加的超时奖励。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.bonus_ge_24000_s',
    defaultValue: '2',
    description: '候选代码 >= 24KB 时，给运行时 QA 追加的超时奖励。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.bonus_ge_32000_s',
    defaultValue: '10',
    description: '候选代码 >= 32KB 时，给运行时 QA 追加的超时奖励。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.bonus_ge_40000_s',
    defaultValue: '4',
    description: '候选代码 >= 40KB 时，给运行时 QA 追加的超时奖励。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.remediation_bonus_per_attempt_s',
    defaultValue: '4',
    description: '运行时 QA 进入 remediation 后，每一轮追加的超时奖励。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.remediation_bonus_max_s',
    defaultValue: '8',
    description: '运行时 QA remediation 追加超时的最大值。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.remediation_large_code_floor_s',
    defaultValue: '8',
    description: '大代码量且进入 remediation 时，运行时 QA 追加超时的保底值。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.load_wait_factor_ms_per_s',
    defaultValue: '250',
    description: '运行时 QA 在 page.load 阶段按有效超时折算出的等待系数。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 'ms',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.load_wait_min_ms',
    defaultValue: '250',
    description: '运行时 QA 等待 load state 的最小等待时间。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 'ms',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.initial_wait_ratio',
    defaultValue: '0.25',
    description: '运行时 QA 在首次渲染后额外等待时间的比例系数。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 'ratio',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.initial_wait_min_s',
    defaultValue: '0.35',
    description: '运行时 QA 首次渲染后额外等待的最小秒数。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.initial_wait_max_s',
    defaultValue: '2',
    description: '运行时 QA 首次渲染后额外等待的最大秒数。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.post_wait_ratio',
    defaultValue: '0.15',
    description: '运行时 QA 注入交互后额外等待时间的比例系数。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 'ratio',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.post_wait_min_s',
    defaultValue: '0.15',
    description: '运行时 QA 注入交互后额外等待的最小秒数。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.runtime_qa.post_wait_max_s',
    defaultValue: '0.8',
    description: '运行时 QA 注入交互后额外等待的最大秒数。',
    service: 'ai-engine',
    group: 'runtime_qa',
    unit: 's',
    valueType: 'float',
  },
  {
    key: 'timeout.ai_engine.llm_activity_heartbeat_s',
    defaultValue: '15',
    description: 'LLM 调用期间 heartbeat activity 的发送间隔。',
    service: 'ai-engine',
    group: 'llm',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.llm_fallback_connect_s',
    defaultValue: '15',
    description: '未命中数据库网关配置时，AI engine 使用环境变量 fallback 路由的 LLM connect timeout。',
    service: 'ai-engine',
    group: 'llm',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.llm_gateway_cache_ttl_s',
    defaultValue: '10',
    description: 'LLM gateway 从数据库刷新 provider/route 配置的缓存时长。',
    service: 'ai-engine',
    group: 'llm',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.timeout_store_cache_ttl_s',
    defaultValue: '10',
    description: 'AI engine timeout 配置缓存从数据库刷新的间隔。',
    service: 'ai-engine',
    group: 'config',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.prompt_store_db_connect_s',
    defaultValue: '5',
    description: 'Prompt store 读取 system_configs / prompt bundles 时的数据库连接超时。',
    service: 'ai-engine',
    group: 'config',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.prompt_store_db_read_s',
    defaultValue: '5',
    description: 'Prompt store 读取 system_configs / prompt bundles 时的数据库读超时。',
    service: 'ai-engine',
    group: 'config',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.gateway_db_connect_s',
    defaultValue: '5',
    description: 'LLM gateway 读取 provider/route 时的数据库连接超时。',
    service: 'ai-engine',
    group: 'config',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.gateway_db_read_s',
    defaultValue: '5',
    description: 'LLM gateway 读取 provider/route 时的数据库读超时。',
    service: 'ai-engine',
    group: 'config',
    unit: 's',
    valueType: 'int',
  },
  {
    key: 'timeout.ai_engine.async_task_completed_ttl_s',
    defaultValue: '86400',
    description: 'AI engine 内存异步任务在完成后保留的时长。',
    service: 'ai-engine',
    group: 'tasking',
    unit: 's',
    valueType: 'int',
  },
];

export const TIMEOUT_CONFIG_CATALOG_BY_KEY = new Map(
  TIMEOUT_CONFIG_CATALOG.map((entry) => [entry.key, entry]),
);
