// Generated by scripts/sync-quality-policy.py; edit the contract.
export const QUALITY_POLICY = {
  "version": "2026-09-07-artifact-v2",
  "tiers": {
    "safe": {
      "fun_score": 6.0,
      "visual_polish_score": 5.8,
      "character_quality_score": 5.2,
      "abstract_character_floor": 4.8,
      "final_score": 5.8
    },
    "standard": {
      "fun_score": 6.8,
      "visual_polish_score": 6.8,
      "character_quality_score": 6.4,
      "abstract_character_floor": 6.0,
      "final_score": 6.6
    },
    "showcase": {
      "fun_score": 8.0,
      "visual_polish_score": 8.0,
      "character_quality_score": 7.5,
      "abstract_character_floor": 7.0,
      "final_score": 8.5,
      "min_review_bonus": -1.5
    }
  },
  "artifact_rubrics": {
    "game": {
      "description": "现有游戏评分：完整可玩、玩法循环、趣味、视觉和角色；按tiers执行门槛。"
    },
    "tool": {
      "description": "功能正确与完整、输入边界、交互反馈、可用性与清晰呈现；不评分游戏趣味和角色。",
      "weights": {
        "functional_correctness": 0.4,
        "interaction_feedback": 0.25,
        "usability": 0.2,
        "visual_clarity": 0.15
      },
      "minimums": {
        "functional_correctness": 7,
        "interaction_feedback": 6.5,
        "usability": 6,
        "visual_clarity": 5
      },
      "pass_score": 7
    },
    "science": {
      "description": "模型公式和单位正确、参数确实影响模型、解释假设与限制、图形可读；不评分游戏趣味。",
      "weights": {
        "scientific_correctness": 0.35,
        "parameter_fidelity": 0.25,
        "explanation_integrity": 0.25,
        "visual_clarity": 0.15
      },
      "minimums": {
        "scientific_correctness": 7,
        "parameter_fidelity": 7,
        "explanation_integrity": 7,
        "visual_clarity": 5
      },
      "pass_score": 7
    }
  }
} as const;
