// Generated by scripts/sync-llm-routing-policy.py; edit the contract.
export const LLM_ROUTING_POLICY = {
  "version": 1,
  "legacyUncheckedFlags": {
    "verified": false,
    "supports_dialogue": false,
    "supports_patch_generation": false,
    "supports_full_html_rewrite": false
  },
  "stages": [
    {
      "id": "generate",
      "name": "作品生成",
      "description": "首次生成与生成后的代码修复",
      "stepKeys": [
        "code_generate.full",
        "quality_gate.patch_fix",
        "qa_fix.syntax_structural"
      ]
    },
    {
      "id": "modify",
      "name": "作品修改",
      "description": "修改分类、参数、内容和玩法调整",
      "stepKeys": [
        "iterate.classify",
        "iterate.param_adjust",
        "iterate.element_change",
        "iterate.mechanic_change"
      ]
    },
    {
      "id": "assist",
      "name": "辅助处理",
      "description": "需求解析、创意整理与质量评审",
      "stepKeys": [
        "intent_parse",
        "creative_anchors",
        "code_review"
      ]
    }
  ],
  "stepCapabilities": {
    "creative_anchors": [
      "supports_dialogue"
    ],
    "code_generate.full": [
      "supports_full_html_rewrite"
    ],
    "quality_gate.patch_fix": [
      "supports_patch_generation"
    ],
    "iterate.mechanic_change": [
      "supports_patch_generation"
    ],
    "iterate.element_change": [
      "supports_patch_generation"
    ],
    "iterate.param_adjust": [
      "supports_patch_generation"
    ],
    "qa_fix.syntax_structural": [
      "supports_full_html_rewrite"
    ],
    "intent_parse": [
      "supports_dialogue"
    ],
    "iterate.classify": [
      "supports_dialogue"
    ]
  }
} as const;
