#!/usr/bin/env python3
"""Generate language-local routing requirements from one contract."""
import argparse
import json
import pprint
from pathlib import Path

root = Path(__file__).resolve().parents[1]
policy = json.loads((root / "contracts/llm/routing-policy.json").read_text())
outputs = {
    root / "packages/ai-engine/src/services/generated_llm_routing_policy.py":
        "# Generated by scripts/sync-llm-routing-policy.py; edit the contract.\nLLM_ROUTING_POLICY = " + pprint.pformat(policy, sort_dicts=False) + "\n",
    root / "packages/game-service/src/admin/generated-llm-routing-policy.ts":
        "// Generated by scripts/sync-llm-routing-policy.py; edit the contract.\nexport const LLM_ROUTING_POLICY = " + json.dumps(policy, ensure_ascii=False, indent=2) + " as const;\n",
}
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for path, expected in outputs.items():
    if args.check:
        if not path.exists() or path.read_text() != expected:
            parser.error(f"Routing policy drift: regenerate {path.relative_to(root)}")
    else:
        path.write_text(expected)
