#!/usr/bin/env python3
"""Generate deployable language-local policies from one versioned contract."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
policy = json.loads((root / "contracts/generation/quality-policy.json").read_text())
serialized = json.dumps(policy, ensure_ascii=False, indent=2)
outputs = {
    root / "packages/ai-engine/src/engine/generated_quality_policy.py":
        '# Generated by scripts/sync-quality-policy.py; edit the contract.\nQUALITY_POLICY = ' + serialized + '\n',
    root / "packages/game-service/src/game/generated-quality-policy.ts":
        '// Generated by scripts/sync-quality-policy.py; edit the contract.\nexport const QUALITY_POLICY = ' + serialized + ' as const;\n',
}
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for path, expected in outputs.items():
    if args.check:
        if not path.exists() or path.read_text() != expected:
            parser.error(f"Policy drift: regenerate {path.relative_to(root)}")
    else:
        path.write_text(expected)
